spring:
  profiles:
    active: dev
  datasource:
    # ?oracle.jdbc.sendBooleanAsNativeBoolean=false for 23ai images and Quartz incompatibility
    # https://github.com/quartz-scheduler/quartz/discussions/1292
    jdbcUrl: jdbc:oracle:thin:@//localhost:1521/FREEPDB1?oracle.jdbc.sendBooleanAsNativeBoolean=false
    username: app_user
    password: spring-quartz-scheduler-oracle-db
    driver-class-name: oracle.jdbc.OracleDriver

  quartz:
    job-store-type: jdbc
    jdbc:
      initialize-schema: never
    wait-for-jobs-to-complete-on-shutdown: true
    properties:
      org:
        quartz:
          threadPool:
            threadCount: 5
          jobStore:
            driverDelegateClass: org.quartz.impl.jdbcjobstore.oracle.OracleDelegate
